language: node_js
node_js:
  - "node"
  - "lts/*"
  - "10" # To keep v10 support alive even when lts shifts to a later version
env:
  global:
    # CODACY_PROJECT_TOKEN
    - secure: uEAtiFXRBXBApNTWULgcIrJU1ZSgvURSGQFDU3nQg7aqRADYJONEaiPvHEgs5ye1w9vVxR5kZWe8OaTuPdSEB7/p6FXyZeCE2d4IqqtgYvHG3/ImDy6QqSWDFXKmsMHb2a2SweNXvZu1nTs5sGB9WlTpanp6z0UN3zw383CEbSRlqHtPZ3/1NkBA19KuIV7qjV7KSUnq7Med/XQtb9ctXAw45CigIsE3pGCjWLW8zjMIYM2whPKd//coQHPWkygRS/U1hhv+BODw2GXE29XUnhrOAMuwR46171H0CCtwFki6b0fict1mFsT0LFyckv1FpLI/yeLGnYr7MNmZ5cGLFu6Iua2U6ZSFcIDrycftjr6fza46RpJtZkdOM3aejAHFVw/MWw766NS3Ap3cuQKh835g5gz3H22e5/qGrDSKx2PVW4SXsmAi/7gQUSpwlNfdLpoi4zOHPzpGdZRcihn6iCnAxJdu2m5+itY3zJeh+v/8PVDBjs1TTmvCVaCUsn0jfY/Bvpw901Y69qMDtcbL7XFTI9liED54ibGSRmXUq74lyNOnxjY5JFgY1f/tG0f9JLyuvb7uBSQmf8RimbOXTBlYmFBhivTnx3GLhqAvOwUssbtGoqMGm5lfM2e/0YgIAivCb9PQVKCASUGIXlZHZebCE9S8jdMR+8MpamTfLJE=
    # GH_TOKEN (Github for semantic-release)
    - secure: "IFeqD171oYso4qAgmv9v9QdIRRymvg2MoYQqDfzONlRDO/pnQh//SixKp5flvzYTfVRdKuRHr5qw5xiDMsLW7mBhvUQqIVGsZMuFsC7Lhk+pGoIK6fjtpzRJDmCcL3dz12xvtXtLxKGWPDs9rF9XMYK1AEERrYc8Jzf6vqw1GmKypriONbps14gLWHyy1rhQTMhpLXhbA00YnnrPuceHtkx/W0Lsj2iE4PAl3B/f7ZPZIcfi+/oMdK1j0geMtVrwtmBCKcdXU7bhgGFX9StcY7J3KE05ZqKBnbE8imDgy0NfjUsRwZ5hEzipnW6pUG/M5BJgp4OvvZru6XXV4b/MRRkXtm7qzlKoWyDrScKT8QquyOTvuXVbJMbP8VjJnEuHVF9EZqksb5GkosTsTK4fyiSZCWupvi/p9zd+VRiUMqc+TWQIi7kz8IWs2Gqy3o2xjr7sv3p9EEou7KpbHQsiwrsHnaTN3iYq6DGhIc5fkn43RXV2bvyGx4pmNGR+obv5f3qo1Wyx9nsANTtlKiVJCmz8OEz6DjyeMZ8bbiEhUQsBYhufFTydBnVsR8nh5CKqcADx2BS6cxBo+WJrsjMBBvM3qq4ussV8fvP/ix/wxEgI5P9VLE+AtqWI3DoPYpiFejYg9sF2JRdK3SmaPeOV+ud8FKyv8Q+2TTr9NEZcuPc="
    # NPM_TOKEN
    - secure: "i9OTdM0/1jpNHOBvEVxOjHq2Y1luFsJQJjikqhZ15DDuu4qQzMxuzxy0eoDz4fqRvtlpVD1kjsFpMV9AZGB1eTrhab1deptISrAnmfgdDyuMA5O8g5Er5NERD8dx22vk3NUpnSIjn2bzHxZfwlbpsDKFGdBqmoI3AR3xmXCabmuKZL57V1jfu5gLKE48TV2/RsuDLIeRSahhM8JpavlsBJ5OdAorLx68BuKKcJRLD38hrZsO4DClK/IXVB7LN3GJy4XyrQWMNmzMQJoHs7HsbNIJ3MGOb5Sh2po8X5jAoGMPOX4F0JsmS3AnFb1KrWZYETvpZcWq1E0p/FV+YlyMz43OLnetgtKaD3xtTvssFwEbRaw9ngoi4q9eBCbJHRXr9BIHiD2t7/dVizymE1umYC81wTmcNr6+nU76AucPFwrTxzvZ1VlOnXUv6lQQ4ChAPdYGc71Jo/77JhgtXnNMGhgUdSncqbt6zLDklIfQkSMiXFHHGsvnAJSE58CtZdX13xC1EUQuE71BUfObTZId7EZkI5IGAGM5XNjYPv8GHi/HTf+EYGO5gtrUoRQcGSxjFM9wk4Nx6P7e32JpjtXxlAF3kQvjil1sb+DQ1yqYYydsAxVUs9Vq14CDZ/5qig6fQcsI8pOkLw2aicUBxCvniv9sRs3WwR7tONHSzFYIBvM="
cache: yarn
script:
  - echo "Running with node version $(node -v) ..."
  - yarn lint
  - yarn test
jobs:
  include:
    - stage: Report Coverage
      node_js: "node"
      script: yarn coverage
    # Define the release stage that runs semantic-release
    - stage: release to npm
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - ./node_modules/.bin/semantic-release
